services:

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: multiview-server-mediamtx
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml:ro

  multiview-server:
    container_name: multiview-server
    build: .
    working_dir: /app
    restart: unless-stopped
    network_mode: host
    environment:
      - NODE_ENV=production
      - PORT=8080
      - TZ=${TZ}
      - MULTIVIEW_PUBLIC_URL=${MULTIVIEW_PUBLIC_URL}
      - MULTIVIEW_DATA_DIR=/app/data
      - MEDIAMTX_API_BASE=${MEDIAMTX_API_BASE}
      - MEDIAMTX_HLS_BASE=${MEDIAMTX_HLS_BASE}
    volumes:
      - ./src:/app
      - ./data:/app/data
      - ./logs:/app/logs
